server:
  port: 8585
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: manager
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: system
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
      
      
  mail:
    host: smtp.gmail.com
    port: 587
    username: chintu.dhananjay04@gmail.com
    password: drktech@123
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
          